# Action Name
name: CI

# when this github action execute
# pull_request -> on pull_request
# push -> on push pr code into master
on:
    pull_request:
        branches:
            - main
    push:
        branches:
            - main

# Jobs -> grouped multiple steps in single group
# 1. before merge
# 2. after merge

# We can run both jobs on separate machines.

jobs:
    build-and-test:
        name: Build the Project
        runs-on: ubuntu-latest
        # this steps execute on those machine where this job runs
        steps:
            - uses: actions/checkout@v3
            - name: Install dependencies
              run: npm ci
            - name: Run eslint
              run: npm run lint
            - name: Run prettier
              run: npm run format:fix
            - name: Test and coverage
              run: npm run test
              env:
                  DB_HOST: ${{ secrets.TEST_DB_HOST }}
                  DB_PORT: ${{ secrets.TEST_DB_PORT }}
                  DB_USERNAME: ${{ secrets.TEST_DB_USERNAME }}
                  DB_PASSWORD: ${{ secrets.TEST_DB_PASSWORD }}
                  DB_NAME: ${{ secrets.TEST_DB_NAME }}
                  REFRESH_SECRET_KEY: ${{ secrets.REFRESH_TOKEN_SECRET }}
                  JWKS_URI: ${{ secrets.JWKS_URI }}
                  PRIVATE_KEY: ${{ secrets.PRIVATE_KEY }}
            - name: Build ts
              run: npm run build
            - name: SonarCloud Scan
              uses: SonarSource/sonarcloud-github-action@master
              env:
                  GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
                  SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}

    # This triggers when code is pushed to the main branch, because this executes on a push event trigger
    build-and-push-docker:
        name: Build and Push Docker Image
        # this will execute when build-and-test job successfully executed
        needs: build-and-test
        runs-on: ubuntu-latest
        env:
            IMAGE_NAME: aakash1707/mernstack-auth-service
            IMAGE_TAG: build-${{ github.run_number }}

            # check condition when to build docker image
            # if main branch and event trigger is push
        if: github.ref == 'refs/heads/main' && github.event_name == 'push'
        steps:
            - name: Checkout repository
              uses: actions/checkout@v3
            - name: Log in to Docker Hub
              uses: docker/login-action@v1
              with:
                  username: ${{ secrets.DOCKERHUB_USERNAME }}
                  password: ${{ secrets.DOCKERHUB_PASSWORD }}
            - name: Build docker image
              run: docker build -t ${{ env.IMAGE_NAME }}:${{ env.IMAGE_TAG }} -f docker/prod/Dockerfile .
            - name: Push docker image to Docker hub
              run: docker push ${{ env.IMAGE_NAME }}:${{ env.IMAGE_TAG }}
